import {
  Card,
  CardHeader,
  CardBody,
  CardFooter,
  Typography,
  Avatar,
  Tooltip,
  Input,
  Checkbox,
  Button,
  IconButton,
} from "@material-tailwind/react";
import { BsGenderMale, BsGenderFemale } from "react-icons/Bs";
import { HiChevronLeft } from "react-icons/hi2";
import { AiFillCamera ,AiOutlineLeft } from "react-icons/ai";
import Menu from "@/components/Menu";
import Image from "next/image";
import Head from "next/head";
import { useAuth } from "@/contexts/AuthContext";
import { useRouter } from "next/router";


// flex justify-center items-center
export default function Setting() {
  const router = useRouter();
  const { currentUser } = useAuth();
  
  return (
    <>
      <Head>
        <title>Dialect on Water</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-hidden bg-white rounded-md bg-white  w-full h-full lg:h-4/5 lg:w-4/5 shadow-lg flex items-center flex-col place-content-start relative">
      {/* header content */}

      <section className="w-full p-8 relative" style={{ "margin-bottom": "10px", "background-color": "rgb(187 222 251)" }}>
        {/* USER ICON */}
        <a>
          <AiOutlineLeft size={50} color="#FFFFFF" onClick={() => router.push("/home")}/>
        </a>
        <button className="mt-5">
          <div className="sm:w-32 sm:h-32 w-20 h-20 rounded-full bg-blue-500 grid justify-center content-center">
            <AiFillCamera className="sm:w-16 sm:h-16 w-12 h-12 z-10 drop-shadow-sm " style={{ "color": "rgb(20 80 107)", }} />
            <div className="sm:w-6 sm:h-6 w-4 h-4 m-2 rounded-full bg-red-800 justify-self-end self-end absolute">
            </div>
          </div>
        </button>
      </section>
      {/* main content */}
      <CardBody className="mb-24 w-full ml-0 md:ml-4 md:mr-4 mr-0">
          {/* form header */}
          <Typography variant="h3" color="blue-gray" className="w-28 md:w-60  md:text-3xl text-base">
            會員資料
          </Typography>

          <form className="md:mt-8 mt-0 mb-2  flex flex-col justify-center overflow-auto" >
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3  justify-evenly overflow-auto mb-26">

              <div className="w-60 h-24">
                <label className="text-xl text-blue-800 font-bold " >用戶名稱</label>
                <Input variant="static" placeholder="username" className="text-xl w-44" />
              </div>
                <div className="w-60 h-32">
                  <p className="text-xl text-blue-800 font-bold " >性別</p> 
                 <span className="text-xl m-3" >男</span> 
                <IconButton color="blue" style={{"minHeight":"65px", "minWidth":"65px"}}>
                    <BsGenderMale className="text-xl" />
                  </IconButton>
                  <span className="text-xl m-3" >女</span> 
                <IconButton color="red" style={{"minHeight":"65px", "minWidth":"65px"}}>
                  <BsGenderFemale className="text-xl"/>
                </IconButton>
              </div>
              <div className="w-60 h-24">
                <label className="text-xl text-blue-800 font-bold " >Email</label>
                <Input variant="static" placeholder="Email" className="text-xl w-52" disabled/>
              </div>

              <div className="w-60 h-24">
                <label className="text-xl text-blue-800 font-bold " >電話號碼</label>
                <Input variant="static" placeholder="Phone number" className="text-xl w-52" disabled/>
              </div>
              <div className="w-60 h-24">
                <label className="text-xl text-blue-800 font-bold " >登入方法</label>
                <Input variant="static" placeholder="Login method" className="text-xl w-52" disabled/>
              </div>
              <div className="w-60 h-24">
                <label className="text-xl text-blue-800 font-bold " >用戶權限</label>
                <Input variant="static" placeholder="Member" className="text-xl w-52" disabled/>
              </div>


            </div>
            <button
              type="submit"
              className="lg:w-auto w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-2xl px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 mb-[300px]"
            >
              上傳水話
            </button>
          </form>

        </CardBody>

     
        <Menu />
      </main>
    </>
  );
}