import SignInPhone from "@/components/SignInPhone";
import Head from "next/head";

export default function PhoneSignIn() {
  return (
    <>
      <Head>
        <title>Sign in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen flex items-center justify-center">
        <SignInPhone />
      </main>
    </>
  );
}
