import Head from "next/head";
import LoginCard from "@/components/LoginCard";

export default function Login() {
  return (
    <>
      <Head>
        <title>Dialect on Water</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen flex items-center justify-center">
        <LoginCard />
      </main>
    </>
  );
}
