import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import LoginCard from "@/components/LoginCard";
import UseRefTest from "@/components/UseRefTest";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Dialect on Water</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen flex items-center justify-center">
        <LoginCard />
        {/* <UseRefTest /> */}
      </main>
    </>
  );
}
