import Head from "next/head";
import Menu from "@/components/Menu";
import DialectList from "@/components/DialectList"
import SignOutButton from "@/components/SignOutButton";
import ItemDetailPage from "@/components/ItemDetailPage"

import { useAuth } from "@/contexts/AuthContext";
import { useRouter } from "next/router";

export default function Home() {
  const { currentUser } = useAuth(); 
  const router = useRouter();


  // if currentUser = "admin"{

  // };
  return (
    <>
      <Head>
        <title>Dialect on Water</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-hidden bg-white rounded-md bg-white  w-full h-full lg:h-4/5 lg:w-4/5 shadow-lg flex items-center flex-col place-content-start relative">
        <ItemDetailPage />
        {/* menu */}
        <Menu />
      </main>
    </>
  );
}
